# 以太坊的重入攻击

代码：

合约A

```
function withdraw()public returns(bool){
  .....             
  (bool success, _) = msg.sender.call{value: balances[msg.sender]};
  if(!success){
    revert("Failed")
  }
  balance[msg.sender] = 0;
  ....
}
```

合约B

```
uint stack = 0;
function fallback() public payable {
    stack += 2;
    if(address(msg.sender).balance>=msg.value && msg.gas>6000 && stack<500){
        A.withdraw();
    }
    
}
```

如上所示，B合约调用A合约的withdraw函数，但是在withdraw函数中进行转账，会回调B合约的fallback，此时A合约记录的余额还没有更新，就会导致合约B重复提现。直到A合约的余额不足为之，或者gas不足，或者栈深度超过500。

如何修复：
先更新A合约的余额为零，再进行转账

